# Based on http://conda.pydata.org/docs/travis.html
language: python
python:
  - "3.6"

install:
  - pip install numpy netCDF4 xarray numba pytest-cov

script:
  - py.test --cov=./

after_success:
  - codecov
