language: python
python:
  - "3.6"

install:
  - pip install numpy netCDF4 xarray numba pytest-cov codecov matplotlib
  - pip install $(cat requirements.txt)

script:
  - py.test --cov=./

after_success:
  - codecov